:: This is an DLN training file generated by test_net.py module@echo off
set PYTHONPATH=%PYTHONPATH%;.
C:\Users\kol\Documents\kol\py2.7\python.exe C:\Users\kol\Documents\kol\py-faster-rcnn\tools\train_net.py --solver C:\Users\kol\Documents\kol\gbr\models\zf_solver.prototxt --imdb gbr_train --iters 10000 --cfg C:\Users\kol\Documents\kol\gbr\models\gbr_rcnn.yml 2>&1 | wtee out\logs\train.log
